### ISSUE TITLE
how to use this with wordpress?

### ISSUE THREAD

**Issue by genius2k** [viljamis/responsive-nav.js#105]
how to use this with wordpress?

**Comment by mizukimadness** [comment]
I didn't use a custom walker class, don't know which way is the correct way but this is what I did.

I put the plug-in in a folder called "responsive nav". To make WordPress find the files, I had to change the links in <head> from this:

<link href="responsive-nav/responsive-nav.css" rel="stylesheet" type="text/css" />
<script src="responsive-nav/responsive-nav.js" />

to this:

<script src="<?php bloginfo('template_url'); ?>/responsive-nav/responsive-nav.js"></script>
<link href="<?php bloginfo('stylesheet_directory'); ?>/responsive-nav/responsive-nav.css" rel="stylesheet" type="text/css" />

To make the plug-in work with a WordPress menu (the ones you can find under "Menus" in WordPress), I followed a tutorial and made sure the "nav-collapse"-class was added to the navigation in the HTML. http://code.tutsplus.com/tutorials/creating-a-wordpress-theme-from-static-html-adding-navigation--wp-34032
