### ISSUE TITLE
Hide responsive menu while loading?

### ISSUE THREAD

**Issue by vincentccw** [viljamis/responsive-nav.js#114]
I've two navigations, a desktop and responsive version. By default I've set media queries to show only one at a time (display: block and display: none)

However when I open the page in smaller screen size the responsive version shows up a fraction of a section and only disappear.

You can see the problem here:
http://wthdesign.net/naber2/products-services.html

How do I prevent user from seeing the responsive menu while loading?
I've tried to set display:none to the responsive menu by default but it will break the trigger button "≡".

**Comment by voodoo6** [comment]
Hi @viljamis there appears to be some code missing from your final comment with instructions how to prevent the brief flashing of the menu while loading – can you provide this again if possible?
Thanks
