### ISSUE TITLE
Tall mobile menu problems - links preventing scroll down page

### ISSUE THREAD

**Issue by o-l-e** [viljamis/responsive-nav.js#117]
Let me start by saying this is a really nice plugin!

I am testing the multiple levels demo http://viljamis.com/demo/responsive-nav-multiple-levels/, and have the following issue:
When on mobile and expanding multiple levels, i try to swipe/scroll further down the menu/page (dragging on the menu area) in order to see the nested menu levels that open. The problem is that something is preventing the default behaviour (touchdrag i think), so i get stuck 8 out of 10 times trying to move further down the page when the menu is expanded and taller than the screen itself. The 2 out 10 tries i do manage to scroll, are the times that i drag on a plain link (not dropdown). This is of course especially noticable when the menu is about three times the height of a landscape mobile screen.

Hope this was understandable, basically i wonder if there is something that can be done to be able to drag/swipe/scroll when placing your finger on a dropdown menu link. It's kind of annoying that the scrolling feels "stuck" when everything with this plugin is so smooth.

Help would be appreciated :)

**Comment by o-l-e** [comment]
Related issue:
https://github.com/viljamis/responsive-nav.js/issues/127

**Comment by viljamis** [comment]
multiple-levels demo is not finished. It’s right now just an experiment and should not be used on a production site.
