### ISSUE TITLE
More than one navigation in one html-document

### ISSUE THREAD

**Issue by pattrisha** [viljamis/responsive-nav.js#124]
Is it possible to have more than one navigation/menu in one html-document? I work with jquery mobile pages and have them all in one html-document. If I try to use multiple menus (one for each jquery mobile page) the menu for small screens only works on one page. Can you help me out?

**Comment by mizukimadness** [comment]
Yes. Just hook up the plug-in again. Say you have a <nav class="global"> and <nav class="left">, you'll need to add the following code just before the closing body tag, to get two responsive menus:

<script>
var nav = responsiveNav("global");
var nav = responsiveNav("left");
</script>

You probably need to add those classes into the responsive-nav.css too to determine the breakpoint and such.
