### ISSUE TITLE
Cannot dismiss dropdown. Also, swipe problem

### ISSUE THREAD

**Issue by piperh** [viljamis/responsive-nav.js#127]
I like this nav solution and would use it on a current job but for two niggling problems:
1. on touch screen wide enough to not need the toggle function, once you have shown a drop-down menu you can't dismiss it by tapping again off the menu.
2. With the menu toggled and showing open on a phone screen in landscape mode where you have little depth of screen, you cannot swipe scroll to get below the opened menu if your first touch happens to be on a link with a submenu. You have to position the finger so as to begin the swipe on a link with no submenu or on the logo.
This is observed on your 'multiple-levels' demo. If it were a css problem I'd dive in, but seems like a script issue and I have no competence in js.

**Comment by o-l-e** [comment]
+1

**Comment by o-l-e** [comment]
related issue here:
https://github.com/viljamis/responsive-nav.js/issues/117

**Comment by viljamis** [comment]
multiple-levels version is not ready and has quite many unfinished parts at the moment, so I’d currently suggest to not use that branch.

**Comment by roman02** [comment]
Is the multiple-levels version version still not ready for use?

**Comment by flepp** [comment]
Strange, I've actually used it on a few projects, works fine. Only part that "doesn't work" : nested ULs don't seem to animate at all (when in dropdown menu mode). Not that big of a deal.
