### ISSUE TITLE
tell people where is the breakpoint

### ISSUE THREAD

**Issue by hedii** [viljamis/responsive-nav.js#131]
Hi, good job :)
I just wanted to tell you that you should write somewhere in your documentation where users have to modify the breackpoint of the navigation menu (@media query in css file).
It is written nowhere on you doc (i think), and i just passed 20min searching for that on available options/js files.
anyway thx for your work

**Comment by gkatsanos** [comment]
+1

**Comment by viljamis** [comment]
This is a good suggestion and I added it to the readme few months ago: https://github.com/viljamis/responsive-nav.js#changing-the-breakpoint
