### ISSUE TITLE
"Menu" label for the toggle should be inside a span (or other element)

### ISSUE THREAD

**Issue by toonvandeputte** [viljamis/responsive-nav.js#132]
Currently, the default menu toggle code looks like this:

````<a href="#" class="nav-toggle" aria-hidden="false">Menu</a>````

I think it would be more flexible if either the `<a>`tag itself were wrapped in a div, or the 'Menu' level in a span, both with relevant classes of course. That way, it would be fairly easy to add an icon, hide text, etc, with good backwards compatibility and without having to change the default toggle code. So that would be something like:

````<div class="nav-toggle-wrapper" aria-hidden="false"><a href="#" class="nav-toggle">Menu</a></div>````

or:

````<a href="#" class="nav-toggle" aria-hidden="false"><span class="nav-toggle-label">Menu</span></a>````

**Comment by BuildMyWeb** [comment]
agreed

**Comment by viljamis** [comment]
I think the default toggle should be as simple as possible. You can always write custom markup for the toggle if you want to.

**Comment by ryanrain** [comment]
the easiest way i found to do this is to specify an element in the label argument you supply, eg: 
    nav = responsiveNav(".navbar-collapse", {
    	label: '<span></span>'
    });
