### ISSUE TITLE
Nav is open on page load in Opera Mini, doesn't close.

### ISSUE THREAD

**Issue by flepp** [viljamis/responsive-nav.js#133]
First off, bravo for this great, very simple to implement plugin. 

I decided to use it on my  personal site after searching the web for a non-jquery toggleable responsive menu. 
I already had all the CSS done, the only thing missing being the right javascript. 
At first it didn't work, but tweaking the options just a bit to adjust to my css styling did it. Or so I thought.

It works without any problems on the few mobile devices I have tested it on up until now. Yesterday though, I realized I hadn't proceeded to test it on opera mini. So I did. And now the nav behaves as described in the title. 

I tried to tweak my css to make it work, with no success. The only modification that did work (for opera mini only) was setting .closed to display:none;. Which is weird.

I noticed that http://www.adtile.me/fixed-nav/ has the same issue as I do on opera mini. 

I guess there is some sort of incompatibility between the way my css is written and the plugin, but I have absolutely no idea what causes the problem. 

Here is the site : http://test1.byethost24.com/
Tweaked plugin options can be found at the bottom of the index.html file.

I'd like to point out I use the opera micro emulator for testing. I also used it to test the adtile fixed nav which didn't work as well as the responsive nav download site, which works.

So if anyone has any idea, I would be eternally greatful

**Comment by viljamis** [comment]
yeah, overflow hidden doesn’t work there unfortunately :(
