### ISSUE TITLE
Prevent menu flashing

### ISSUE THREAD

**Issue by msavov** [viljamis/responsive-nav.js#134]
How can I prevent menu flashing in a website? This happens on responsive, when I open the site, the menu is already opened, and when the site is loaded completely, it collapse immediately. 

Also, I'm facing with this type of error:
Error: The nav element you are trying to select doesn't exist
Any solutions for solving this?

**Comment by viljamis** [comment]
@msavov You can hide it immediately by adding this one line of JavaScript to the <head> of your site. It "flashes" because the whole plugin is designed progressive enhancement in mind and will hence "flash" before the JavaScript in the footer has loaded:

```
<script>
   document.documentElement.className += " js";
</script>
```

**Comment by aaronstpierre** [comment]
Hi, 

I've added the above code to the <head> but I'm still seeing the menu on page load.  I'm not sure how to stop this from happening. 

Thanks,
Aaron

**Comment by Aybee** [comment]
Your navigation `div#defaultControl_ctl00_segment46_ctl00_place32_ctl00_navigationList` has no `class="nav-collapse"`. Although you see `class="nav-collapse"` with JS enabled but this is too late.

**Comment by johnildo** [comment]
Hi, I'm having the same issue.

Did it get sorted? I didn't understand what exactly is the solution.

https://github.com/viljamis/responsive-nav.js/issues/201

Thank you very much,
J
