### ISSUE TITLE
`disable-pointer-events` not removed after fast touches

### ISSUE THREAD

**Issue by bez4pieci** [viljamis/responsive-nav.js#145]
After tapping the menu toggle for a few times (3 is enough) in quick successtion the `disable-pointer-events` class stays on `body` element. Nothing responds touch events after that. Case: https://froont.com/click/responsive-nav-problem

**Comment by gkatsanos** [comment]
+1 this crashes the browser completely on a quite new phone (iphone6)

**Comment by viljamis** [comment]
I’m gonna try come up with a fix for this issue during the next weekend (probably gonna get a rid of disabling pointer events logic completely and use a better method instead).

**Comment by dwurster** [comment]
+1 (the fix would make me happy as well)

**Comment by TheDistantSea** [comment]
:+1:

**Comment by danbender** [comment]
Thank you, much appreciated. :+1:

**Comment by bez4pieci** [comment]
@viljamis, perfect, thank you!

**Comment by viljamis** [comment]
This is now fixed.
