### ISSUE TITLE
Is it possible to insert a piece of HTML as a label instead of a plain string?

### ISSUE THREAD

**Issue by gkatsanos** [viljamis/responsive-nav.js#147]
Is it possible to insert a piece of HTML as a label instead of a plain string?
I looked through the issue queue, didn't see any related question..

**Comment by VeggieVeggieFruitFruit** [comment]
This probably isn't  the most elegant method but I did figure out how to do a custom label.

This goes at the bottom of the page:

    <script>
      var navigation1 = responsiveNav(".nav-1");
      var navigation = responsiveNav(".nav-1.nav-collapse", {
        customToggle: "#toggle1"
      });
    </script>

You can then style the toggle label in css.  #toggle1{styles go here} 

And then above your menu ul, you put this:

```html
<div id="toggle1" class="nav-toggle" aria-hidden="false"> YOUR TEXT HERE </div>
<nav class="nav-1 nav-collapse"> 
```
And don't forget to close out the div and nav.

The label only shows when your menu collapses.

Hope this helps. I know it's a little late.
