### ISSUE TITLE
Menu is not switching when going fullscreen

### ISSUE THREAD

**Issue by JackiiBE** [viljamis/responsive-nav.js#148]
The menu is working. But it's showing the mobile menu all the time. 
When i resize my browser window to fullscreen it won't switch to the normal menu.
My menu is similar to the 'advanced' demo.

I noticed the "aria-hidden" not changing. It's always set to true.
Anyone wanna help me out?

**Comment by flepp** [comment]
Have you fiddled with the options ? Are you using custom CSS ?

**Comment by JackiiBE** [comment]
I didn't touch the script options. I'm using a custom css yes. How can i share the code with you?

**Comment by JackiiBE** [comment]
Here is the code:
https://gist.github.com/07f0773cfee04d260f94.git

**Comment by flepp** [comment]
Alright, this may be a quick fix, but it should do the trick (worked for me).

Adjust the max-height of .js .nav-collapse (e.g 50px)

Add these to the breakpoint of your choice, and you should be ok.

.js .nav-collapse ul li{

	float: left;
	width:16.666%;

}

.nav-toggle{

	display: none;
}
