### ISSUE TITLE
Custom Toggle hides navigation on larger devices

### ISSUE THREAD

**Issue by rafaeldedos** [viljamis/responsive-nav.js#151]
I created a custom image, added an ID to it and i'm using the "customToggle" option.
Before the breakpoint (768px) it works perfectly, as expected.

But after the breakpoint, on larger screens, the custom image continues showing and the menu is hidden, so i have to click it, which is not desired.

When i turn off customToggle and leave the plugin working as-is, it works perfectly (The word "Menu" appears on mobile and disappears on larger devices).

I searched through the issues before posting this, I'm sorry if I'm missing something very obvious.

Thanks.

**Comment by 3rror404** [comment]
I can also confirm this behaviour

**Comment by viljamis** [comment]
It seems that the custom toggle demo provided was just missing a media query that hides the toggle. Added it there now while also releasing a new version.
