### ISSUE TITLE
General CSS might mess up other CSS above breakpoint

### ISSUE THREAD

**Issue by maspiter** [viljamis/responsive-nav.js#152]
The instructions suppose a situation where the CSS for your plugin comes before all the other CSS. In my case, this messed up some of my desired CSS.

As far as I can tell, the "general" CSS only applies below the breakpoint, so why isn't it included in a media query i.e. @ max-width: 40em (or corresponding to other breakpoint)?

This way, it doesn't get in the way of other CSS rules.

**Comment by viljamis** [comment]
This is because the plugin is designed "mobile first" and progressive enhancement in mind. If you want, you can always change the css to use max-widths instead of min-widths.
