### ISSUE TITLE
Responsive nav working at all in latest Chrome - not even the demo

### ISSUE THREAD

**Issue by mizukimadness** [viljamis/responsive-nav.js#154]
Hello!

The plugin seems to be incompatible with the latest version of Chrome. I'm currently on windows 7 computer with Chrome version 40.0.2214.111. The navigation doesn't even work on the demo site so it's not just something with my own project. It's not collapsing/showing, sometimes it shows when I scroll down and then up again. It works perfectly with FireFox, though.

**Comment by mizukimadness** [comment]
Seems to be a Chrome bug with CSS3 transitions, as I also have problems with some jQuery stuff.

**Comment by dmitrykiselyov** [comment]
Windows 7 Chrome version 41.0.2272.101 m all is well :ok_hand:

**Comment by viljamis** [comment]
Working perfectly here on both mobile and desktop versions of Chrome, closing this for now.
