### ISSUE TITLE
Functionality disappears in landscape mode

### ISSUE THREAD

**Issue by bonilladisseny** [viljamis/responsive-nav.js#157]
It seems that the menu functionality disappears in landscape orientation, I mean in portrait works ok, then change to lanscape and menu is deployed and menu label disappeared. So try to reload the page if it is related with the change of orientation but nothing has changed menu deployed and label missing.

btw had to overwrite max-height because it just show the first menu item, I believe is something related with the hidden accessibility links.

**Comment by viljamis** [comment]
This happens because the media query that hides label kicks in. This is on purpose. You can change this behaviour by changing the breakpoint in the CSS.
