### ISSUE TITLE
How to use Font Awesome instead of string "menu"?

### ISSUE THREAD

**Issue by SmashKazu** [viljamis/responsive-nav.js#160]
Hey Guys,

I would like to use the 3 bars of Font Awesome instead of a label like "menu" or image.

Is there a way to do this? If so, would someone kindly explain it to me?

**Comment by viljamis** [comment]
@SmashKazu Yes there is. Advanced demo already uses icon font, take a look: https://github.com/viljamis/responsive-nav.js/blob/master/demos/advanced/styles.css#L159
