### ISSUE TITLE
_calcHeight and padding of UL

### ISSUE THREAD

**Issue by Zakay** [viljamis/responsive-nav.js#162]
Why isn't height fetched from: nav.inner[0].offsetHeight ?

I'm having issues when styling the UL.

**Comment by viljamis** [comment]
Please take a look of https://github.com/viljamis/responsive-nav.js#things-to-keep-in-mind , this behaviour is on purpose.

**Comment by Zakay** [comment]
That note tells me to style the UL with padding which I'm trying todo
that's the issue I actually have. I'm following the tip.

**Comment by viljamis** [comment]
@Zakay Ah, ok, reopened this issue! Could you provide the code you’re using so I could take a look and try to fix the issue?

**Comment by Zakay** [comment]
@viljamis Sorry, I've tried reproducing it and I can't, maybe I had a old css rule which affected this, cause I've done some refactoring and it works just fine now.

**Comment by viljamis** [comment]
@Zakay ok, good that you got it solved. Let me know if you still experience this issue.
