### ISSUE TITLE
bug appearance on load

### ISSUE THREAD

**Issue by johnildo** [viljamis/responsive-nav.js#201]
Hi,

The toggle menu is working almost perfectly, despite for this issue when it first load.

**When loading the page, the toggle flashes up the list without style.**
http://dev.theoutlookforsomeday.net/
login: cm / tofsdev

I tried all the things I could think of, in css, and some in js.

Does anyone know how to fix it?
Otherwise I'll need to change to another option... :(

Thanks,
J

**Comment by LucyI** [comment]
Take a look at this issue, there's a fix:
https://github.com/viljamis/responsive-nav.js/issues/134

**Comment by johnildo** [comment]
Thanks LucyI!!
I found the solution there!
