### ISSUE TITLE
position: fixed on the navigation bar?

### ISSUE THREAD

**Issue by sunu** [viljamis/responsive-nav.js#62]
I can not seem to make the navigation bar stay fixed at the top. I have tried adding 

```
    position: fixed;
    top: 0;
    left: 0;
```

But it does not seem to work. Any ideas how can I get this working?

**Comment by mattypants** [comment]
I decided to go for absolute instead of fixed; I just want the mobile version of the nav to overlap content underneath, so I used position:absolute;width:100% on the nav's container.
