### ISSUE TITLE
How to set the navigation menu to slide over page content?

### ISSUE THREAD

**Issue by benfoster** [viljamis/responsive-nav.js#94]
Hi Viljami,

Thanks for a great plugin.

Is it possible to configure the navigation menu to slide _over_ the page content rather than pushing the entire content down?

**Comment by mizukimadness** [comment]
I want to do this as well, but I can't find these examples you talked about. Do you have a link to them or something?

**Comment by mizukimadness** [comment]
I solved this putting the navigation in a div, and then using position:absolute on the wrapper div.
